
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'lineADD ASIG BRA DIV ID KET MULT NL NUMBER SUBline : rl \n            | rl NLrl : rl ADD rq\n            | rl SUB rq\n            | rqrq : ket braket : KETbra : BRA'
    
_lr_action_items = {'KET':([0,7,8,],[5,5,5,]),'$end':([1,2,3,6,9,10,11,12,],[0,-1,-5,-2,-6,-8,-3,-4,]),'NL':([2,3,9,10,11,12,],[6,-5,-6,-8,-3,-4,]),'ADD':([2,3,9,10,11,12,],[7,-5,-6,-8,-3,-4,]),'SUB':([2,3,9,10,11,12,],[8,-5,-6,-8,-3,-4,]),'BRA':([4,5,],[10,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'rl':([0,],[2,]),'rq':([0,7,8,],[3,11,12,]),'ket':([0,7,8,],[4,4,4,]),'bra':([4,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> rl','line',1,'p_line','parser.py',11),
  ('line -> rl NL','line',2,'p_line','parser.py',12),
  ('rl -> rl ADD rq','rl',3,'p_rl','parser.py',17),
  ('rl -> rl SUB rq','rl',3,'p_rl','parser.py',18),
  ('rl -> rq','rl',1,'p_rl','parser.py',19),
  ('rq -> ket bra','rq',2,'p_rq','parser.py',28),
  ('ket -> KET','ket',1,'p_ket','parser.py',33),
  ('bra -> BRA','bra',1,'p_bra','parser.py',38),
]
